services:
    reapi-web:
        build: .
        command: ["/usr/bin/supervisord"]
        container_name: reapi-py
        restart: unless-stopped
        env_file:
            - .env
        volumes:
            - .:/usr/src/app
        ports:
            - "8368:8000"
        networks:
            - reapi-net

networks:
    reapi-net:
        driver: bridge
